# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=10, verbose_name='\u540d\u5b57')),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'us_table',
            },
        ),
    ]
